"""
app.py — Flask Web Application
================================
Run: python app.py
Open: http://127.0.0.1:5000

Pages:
  /           → Input form + prediction (both models shown side by side)
  /compare    → Full model comparison dashboard (metrics, charts, confusion matrix)
  /api/predict  → JSON prediction API

ALL models are trained locally. No external API is called.
"""

import json
import os

import joblib
import numpy as np
from flask import Flask, jsonify, render_template_string, request

# ─────────────────────────────────────────────────────────────────────────────
# Load artefacts (generated by train_models.py)
# ─────────────────────────────────────────────────────────────────────────────
BASE      = os.path.dirname(os.path.abspath(__file__))
MDL       = os.path.join(BASE, "models")

lr_model  = joblib.load(f"{MDL}/logistic_regression.pkl")
rf_model  = joblib.load(f"{MDL}/random_forest.pkl")
scaler    = joblib.load(f"{MDL}/scaler.pkl")

with open(f"{MDL}/metrics.json")            as f: METRICS      = json.load(f)
with open(f"{MDL}/feature_importance.json") as f: FEAT_IMP     = json.load(f)
with open(f"{MDL}/roc_data.json")           as f: ROC_DATA     = json.load(f)
with open(f"{MDL}/dataset_summary.json")    as f: DS_SUMMARY   = json.load(f)

CLASS_NAMES = ["A", "B", "C", "D", "F"]
GRADE_DESC  = {
    "A": "Excellent — GPA ≥ 3.5",
    "B": "Good — 3.0 ≤ GPA < 3.5",
    "C": "Satisfactory — 2.5 ≤ GPA < 3.0",
    "D": "Needs Improvement — 2.0 ≤ GPA < 2.5",
    "F": "At Risk — GPA < 2.0",
}
FEATURE_COLS = DS_SUMMARY["feature_columns"]

app = Flask(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Helper
# ─────────────────────────────────────────────────────────────────────────────
def run_prediction(feature_dict):
    row    = np.array([[float(feature_dict[c]) for c in FEATURE_COLS]])
    lr_in  = scaler.transform(row)
    rf_in  = row

    lr_idx   = int(lr_model.predict(lr_in)[0])
    lr_probs = lr_model.predict_proba(lr_in)[0].tolist()

    rf_idx   = int(rf_model.predict(rf_in)[0])
    rf_probs = rf_model.predict_proba(rf_in)[0].tolist()

    return {
        "Logistic Regression": {
            "grade": CLASS_NAMES[lr_idx],
            "desc":  GRADE_DESC[CLASS_NAMES[lr_idx]],
            "probs": {CLASS_NAMES[i]: round(p * 100, 1) for i, p in enumerate(lr_probs)},
        },
        "Random Forest": {
            "grade": CLASS_NAMES[rf_idx],
            "desc":  GRADE_DESC[CLASS_NAMES[rf_idx]],
            "probs": {CLASS_NAMES[i]: round(p * 100, 1) for i, p in enumerate(rf_probs)},
        },
    }

# ─────────────────────────────────────────────────────────────────────────────
# Shared CSS / JS
# ─────────────────────────────────────────────────────────────────────────────
SHARED_HEAD = """
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
:root {
  --ink:      #14213d;
  --ink2:     #2b3a5c;
  --paper:    #f6f3ec;
  --card:     #ffffff;
  --amber:    #c9852b;
  --amber-lt: #f0dcb8;
  --line:     #dcd5c5;
  --a: #2f7a52; --b: #3b7a5e; --c: #b8860b; --d: #b5651d; --f: #a33b2c;
}
*{box-sizing:border-box;margin:0;padding:0;}
body{background:var(--paper);color:var(--ink);font-family:'Inter',sans-serif;font-size:14px;line-height:1.5;}
a{color:var(--amber);text-decoration:none;}
a:hover{text-decoration:underline;}

/* NAV */
nav{background:var(--ink);padding:0 32px;display:flex;align-items:center;gap:0;border-bottom:3px solid var(--amber);}
nav .brand{font-weight:700;font-size:16px;color:#fff;padding:16px 0;margin-right:32px;white-space:nowrap;}
nav a.tab{color:#a8b8d0;padding:18px 20px;font-size:13px;font-weight:600;border-bottom:3px solid transparent;margin-bottom:-3px;display:inline-block;}
nav a.tab:hover{color:#fff;text-decoration:none;}
nav a.tab.active{color:#fff;border-bottom-color:var(--amber);}

/* LAYOUT */
.page{max-width:1100px;margin:0 auto;padding:32px 20px 80px;}
.page-title{font-size:22px;font-weight:700;margin-bottom:4px;}
.page-sub{color:#6b6050;font-size:13px;margin-bottom:28px;}

/* GRID */
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:20px;}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;}
@media(max-width:700px){.grid2,.grid3{grid-template-columns:1fr;}}

/* CARD */
.card{background:var(--card);border:1px solid var(--line);border-radius:6px;padding:24px;}
.card-title{font-size:15px;font-weight:700;margin-bottom:16px;padding-bottom:10px;border-bottom:1px solid var(--line);}

/* FORM */
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;}
@media(max-width:500px){.form-grid{grid-template-columns:1fr;}}
.field label{display:block;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:#6b6050;margin-bottom:4px;}
.field input,.field select{width:100%;padding:9px 10px;border:1px solid var(--line);border-radius:4px;font-family:'Inter',sans-serif;font-size:13px;background:#faf9f5;color:var(--ink);}
.field input:focus,.field select:focus{outline:2px solid var(--amber);border-color:var(--amber);}
.field .hint{font-family:'JetBrains Mono',monospace;font-size:10px;color:#a09070;margin-top:3px;}

/* BTN */
.btn{display:inline-block;padding:11px 28px;background:var(--ink);color:#fff;border:none;border-radius:4px;font-size:14px;font-weight:600;cursor:pointer;transition:background .15s;}
.btn:hover{background:var(--ink2);}
.btn-full{width:100%;text-align:center;}

/* GRADE BADGE */
.grade-badge{font-size:52px;font-weight:700;line-height:1;padding:8px 22px;border-radius:6px;display:inline-block;margin-bottom:6px;}
.grade-A{background:#d4f0e2;color:var(--a);}
.grade-B{background:#d4edd8;color:var(--b);}
.grade-C{background:#fdefc3;color:var(--c);}
.grade-D{background:#ffe0b2;color:var(--d);}
.grade-F{background:#fce4e1;color:var(--f);}
.grade-desc{font-size:13px;color:#5a5040;margin-bottom:18px;}

/* PROB BARS */
.prob-row{display:flex;align-items:center;gap:10px;margin-bottom:8px;}
.prob-lbl{width:16px;font-family:'JetBrains Mono',monospace;font-weight:700;font-size:12px;}
.prob-track{flex:1;background:#ece7d8;border-radius:3px;height:8px;overflow:hidden;}
.prob-fill{height:100%;border-radius:3px;transition:width .4s ease;}
.prob-val{width:40px;text-align:right;font-family:'JetBrains Mono',monospace;font-size:11px;color:#6b6050;}

/* METRIC BOXES */
.metric-box{background:var(--card);border:1px solid var(--line);border-radius:6px;padding:16px;text-align:center;}
.metric-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#6b6050;margin-bottom:6px;}
.metric-val{font-family:'JetBrains Mono',monospace;font-size:22px;font-weight:700;color:var(--ink);}
.metric-sub{font-size:11px;color:#8b8270;margin-top:4px;}

/* TABLE */
table{width:100%;border-collapse:collapse;font-size:13px;}
th{background:var(--ink);color:#fff;padding:10px 12px;text-align:left;font-size:12px;}
td{padding:9px 12px;border-bottom:1px solid var(--line);}
tr:last-child td{border-bottom:none;}
tr:nth-child(even) td{background:#faf9f5;}
.winner{color:var(--a);font-weight:700;}
.badge{display:inline-block;background:var(--amber-lt);color:#7c4f00;border-radius:20px;padding:1px 10px;font-size:11px;font-weight:600;}

/* AGREE / DISAGREE */
.agree{background:#d4f0e2;color:var(--a);border-radius:6px;padding:10px 16px;font-weight:600;margin-top:12px;font-size:13px;}
.disagree{background:#fce4e1;color:var(--f);border-radius:6px;padding:10px 16px;font-weight:600;margin-top:12px;font-size:13px;}

/* CANVAS */
.chart-box{position:relative;height:260px;}

/* SECTION */
.section{margin-bottom:36px;}
.section-title{font-size:16px;font-weight:700;margin-bottom:14px;display:flex;align-items:center;gap:8px;}
.section-title::after{content:'';flex:1;height:1px;background:var(--line);}
</style>
"""

# ─────────────────────────────────────────────────────────────────────────────
# HOME — Prediction Page
# ─────────────────────────────────────────────────────────────────────────────
INDEX_HTML = """
<!DOCTYPE html>
<html lang="en">
<head><title>Student Grade Predictor</title>""" + SHARED_HEAD + """
</head>
<body>
<nav>
  <span class="brand">🎓 Student ML</span>
  <a class="tab active" href="/">Predict</a>
  <a class="tab" href="/compare">Compare Models</a>
</nav>

<div class="page">
  <div class="page-title">Student Grade Predictor</div>
  <div class="page-sub">Enter student details below — both Logistic Regression and Random Forest will predict the grade simultaneously.</div>

  <form method="POST" action="/">
    <div class="grid2" style="align-items:start;">

      <!-- LEFT: Input Form -->
      <div class="card">
        <div class="card-title">📋 Student Profile</div>
        <div class="form-grid">

          <div class="field">
            <label>Age</label>
            <select name="Age">
              {% for v in [15,16,17,18] %}
              <option value="{{v}}" {{'selected' if submitted and submitted.Age==v|string else ''}}>{{v}}</option>
              {% endfor %}
            </select>
          </div>

          <div class="field">
            <label>Gender</label>
            <select name="Gender">
              <option value="0" {{'selected' if submitted and submitted.Gender=='0'}}>Male</option>
              <option value="1" {{'selected' if submitted and submitted.Gender=='1'}}>Female</option>
            </select>
          </div>

          <div class="field">
            <label>Ethnicity</label>
            <select name="Ethnicity">
              <option value="0">Caucasian</option>
              <option value="1">African American</option>
              <option value="2">Asian</option>
              <option value="3">Other</option>
            </select>
          </div>

          <div class="field">
            <label>Parental Education</label>
            <select name="ParentalEducation">
              <option value="0">None</option>
              <option value="1">High School</option>
              <option value="2" selected>Some College</option>
              <option value="3">Bachelor's</option>
              <option value="4">Higher</option>
            </select>
          </div>

          <div class="field">
            <label>Weekly Study Hours</label>
            <input type="number" name="StudyTimeWeekly" min="0" max="20" step="0.5"
              value="{{ submitted.StudyTimeWeekly if submitted else '10' }}" required>
            <div class="hint">0 – 20 hours</div>
          </div>

          <div class="field">
            <label>Absences (days/year)</label>
            <input type="number" name="Absences" min="0" max="30" step="1"
              value="{{ submitted.Absences if submitted else '5' }}" required>
            <div class="hint">0 – 30 days</div>
          </div>

          <div class="field">
            <label>Tutoring</label>
            <select name="Tutoring">
              <option value="0">No</option>
              <option value="1">Yes</option>
            </select>
          </div>

          <div class="field">
            <label>Parental Support</label>
            <select name="ParentalSupport">
              <option value="0">None</option>
              <option value="1">Low</option>
              <option value="2" selected>Moderate</option>
              <option value="3">High</option>
              <option value="4">Very High</option>
            </select>
          </div>

          <div class="field">
            <label>Extracurricular</label>
            <select name="Extracurricular">
              <option value="0">No</option><option value="1">Yes</option>
            </select>
          </div>

          <div class="field">
            <label>Sports</label>
            <select name="Sports">
              <option value="0">No</option><option value="1">Yes</option>
            </select>
          </div>

          <div class="field">
            <label>Music</label>
            <select name="Music">
              <option value="0">No</option><option value="1">Yes</option>
            </select>
          </div>

          <div class="field">
            <label>Volunteering</label>
            <select name="Volunteering">
              <option value="0">No</option><option value="1">Yes</option>
            </select>
          </div>

        </div>
        <div style="margin-top:20px;">
          <button class="btn btn-full" type="submit">⚡ Predict with Both Models</button>
        </div>
      </div>

      <!-- RIGHT: Results -->
      <div>
        {% if result %}

          <!-- Agreement banner -->
          {% set lr_g = result['Logistic Regression']['grade'] %}
          {% set rf_g = result['Random Forest']['grade'] %}
          {% if lr_g == rf_g %}
          <div class="agree">✅ Both models agree: Grade <strong>{{ lr_g }}</strong></div>
          {% else %}
          <div class="disagree">⚠️ Models disagree — LR: <strong>{{ lr_g }}</strong> · RF: <strong>{{ rf_g }}</strong></div>
          {% endif %}

          <div style="height:14px;"></div>

          {% for model_name, res in result.items() %}
          <div class="card" style="margin-bottom:14px;">
            <div class="card-title">{{ model_name }}</div>
            <div class="grade-badge grade-{{ res.grade }}">{{ res.grade }}</div>
            <div class="grade-desc">{{ res.desc }}</div>

            {% for cls, pct in res.probs.items() %}
            <div class="prob-row">
              <span class="prob-lbl">{{ cls }}</span>
              <div class="prob-track">
                <div class="prob-fill" style="width:{{ pct }}%;background:
                  {% if cls=='A' %}var(--a){% elif cls=='B' %}var(--b){% elif cls=='C' %}var(--c){% elif cls=='D' %}var(--d){% else %}var(--f){% endif %};"></div>
              </div>
              <span class="prob-val">{{ pct }}%</span>
            </div>
            {% endfor %}
          </div>
          {% endfor %}

          <!-- Probability comparison chart -->
          <div class="card">
            <div class="card-title">Probability Comparison</div>
            <div class="chart-box">
              <canvas id="probChart"></canvas>
            </div>
          </div>

          <script>
          const ctx = document.getElementById('probChart').getContext('2d');
          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: {{ result['Logistic Regression']['probs'].keys()|list|tojson }},
              datasets: [
                {
                  label: 'Logistic Regression',
                  data: {{ result['Logistic Regression']['probs'].values()|list|tojson }},
                  backgroundColor: '#14213d',
                  borderRadius: 3,
                },
                {
                  label: 'Random Forest',
                  data: {{ result['Random Forest']['probs'].values()|list|tojson }},
                  backgroundColor: '#c9852b',
                  borderRadius: 3,
                }
              ]
            },
            options: {
              responsive: true, maintainAspectRatio: false,
              plugins: { legend: { position: 'bottom' } },
              scales: {
                y: { beginAtZero: true, max: 100, title: { display: true, text: 'Probability (%)' } },
                x: { title: { display: true, text: 'Grade Class' } }
              }
            }
          });
          </script>

        {% else %}
          <div class="card" style="text-align:center;padding:60px 20px;color:#8b8270;">
            <div style="font-size:40px;margin-bottom:12px;">📊</div>
            <div style="font-size:15px;font-weight:600;margin-bottom:6px;">No prediction yet</div>
            <div style="font-size:13px;">Fill in the student profile on the left<br>and click <strong>Predict with Both Models</strong>.</div>
          </div>
        {% endif %}
      </div>

    </div>
  </form>
</div>
</body>
</html>
"""

# ─────────────────────────────────────────────────────────────────────────────
# COMPARE — Full Model Comparison Dashboard
# ─────────────────────────────────────────────────────────────────────────────
COMPARE_HTML = """
<!DOCTYPE html>
<html lang="en">
<head><title>Model Comparison Dashboard</title>""" + SHARED_HEAD + """
</head>
<body>
<nav>
  <span class="brand">🎓 Student ML</span>
  <a class="tab" href="/">Predict</a>
  <a class="tab active" href="/compare">Compare Models</a>
</nav>

<div class="page">
  <div class="page-title">Model Comparison Dashboard</div>
  <div class="page-sub">Logistic Regression vs Random Forest — trained on the Kaggle Students Performance Dataset (2,392 records)</div>

  <!-- ── METRICS ── -->
  <div class="section">
    <div class="section-title">Performance Metrics</div>
    <div class="grid2">
      {% for model_name in ['Logistic Regression', 'Random Forest'] %}
      {% set m = metrics[model_name] %}
      <div class="card">
        <div class="card-title">{{ model_name }}</div>
        <div class="grid3" style="gap:10px;margin-bottom:0;">
          <div class="metric-box">
            <div class="metric-label">Accuracy</div>
            <div class="metric-val">{{ "%.1f"|format(m.accuracy*100) }}%</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">Precision</div>
            <div class="metric-val">{{ "%.1f"|format(m.precision*100) }}%</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">Recall</div>
            <div class="metric-val">{{ "%.1f"|format(m.recall*100) }}%</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">F1-Score</div>
            <div class="metric-val">{{ "%.1f"|format(m.f1_score*100) }}%</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">ROC-AUC</div>
            <div class="metric-val">{{ "%.4f"|format(m.roc_auc) }}</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">Train Time</div>
            <div class="metric-val" style="font-size:16px;">{{ m.train_time_sec }}s</div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- ── COMPARISON TABLE ── -->
  <div class="section">
    <div class="section-title">Side-by-Side Comparison</div>
    <div class="card" style="padding:0;overflow:hidden;">
      <table>
        <thead>
          <tr>
            <th>Metric</th>
            <th>Logistic Regression</th>
            <th>Random Forest</th>
            <th>Winner</th>
          </tr>
        </thead>
        <tbody>
          {% set lr = metrics['Logistic Regression'] %}
          {% set rf = metrics['Random Forest'] %}
          {% for row in [
            ('Accuracy',   lr.accuracy,   rf.accuracy,   True),
            ('Precision',  lr.precision,  rf.precision,  True),
            ('Recall',     lr.recall,     rf.recall,     True),
            ('F1-Score',   lr.f1_score,   rf.f1_score,   True),
            ('ROC-AUC',    lr.roc_auc,    rf.roc_auc,    True),
            ('Train Time', lr.train_time_sec, rf.train_time_sec, False),
          ] %}
          {% set label, lv, rv, higher_better = row %}
          {% set lr_better = (lv > rv) if higher_better else (lv < rv) %}
          <tr>
            <td><strong>{{ label }}</strong></td>
            <td {% if lr_better %}class="winner"{% endif %}>
              {{ "%.4f"|format(lv) }}{% if label not in ['ROC-AUC','Train Time'] %} ({{ "%.1f"|format(lv*100) }}%){% endif %}
              {% if lr_better %} ✅{% endif %}
            </td>
            <td {% if not lr_better %}class="winner"{% endif %}>
              {{ "%.4f"|format(rv) }}{% if label not in ['ROC-AUC','Train Time'] %} ({{ "%.1f"|format(rv*100) }}%){% endif %}
              {% if not lr_better %} ✅{% endif %}
            </td>
            <td>
              <span class="badge">{{ 'Logistic Regression' if lr_better else 'Random Forest' }}</span>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <!-- ── BAR CHARTS ── -->
  <div class="section">
    <div class="section-title">Visual Comparison</div>
    <div class="grid2">
      <div class="card">
        <div class="card-title">Metrics Bar Chart</div>
        <div class="chart-box">
          <canvas id="metricChart"></canvas>
        </div>
      </div>
      <div class="card">
        <div class="card-title">Training Time (seconds)</div>
        <div class="chart-box">
          <canvas id="timeChart"></canvas>
        </div>
      </div>
    </div>
  </div>

  <!-- ── CONFUSION MATRICES ── -->
  <div class="section">
    <div class="section-title">Confusion Matrices (Test Set)</div>
    <div class="grid2">
      {% for model_name in ['Logistic Regression', 'Random Forest'] %}
      <div class="card">
        <div class="card-title">{{ model_name }}</div>
        <div style="overflow-x:auto;">
          <table style="font-size:12px;text-align:center;min-width:300px;">
            <thead>
              <tr>
                <th style="background:#f6f3ec;color:#6b6050;">Actual ↓ / Pred →</th>
                {% for cls in class_names %}<th>{{ cls }}</th>{% endfor %}
              </tr>
            </thead>
            <tbody>
              {% for i, row in enumerate(metrics[model_name]['confusion_matrix']) %}
              <tr>
                <td style="font-weight:700;background:#f6f3ec;">{{ class_names[i] }}</td>
                {% for j, val in enumerate(row) %}
                <td style="
                  font-family:'JetBrains Mono',monospace;
                  background: {% if i==j %}rgba(14,33,61,{{ [val/30,0.85]|min }}){% else %}{% if val>0 %}rgba(163,59,44,{{ [val/30,0.4]|min }}){% else %}#fff{% endif %}{% endif %};
                  color: {% if i==j or val>5 %}#fff{% else %}var(--ink){% endif %};
                  font-weight: {% if i==j %}700{% else %}400{% endif %};
                ">{{ val }}</td>
                {% endfor %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- Per-class recall -->
        <div style="margin-top:14px;display:flex;gap:8px;flex-wrap:wrap;">
          {% for i, cls in enumerate(class_names) %}
          {% set total = metrics[model_name]['confusion_matrix'][i]|sum %}
          {% set correct = metrics[model_name]['confusion_matrix'][i][i] %}
          {% set recall = (correct / total * 100) if total > 0 else 0 %}
          <div style="text-align:center;flex:1;min-width:40px;">
            <div style="font-size:10px;font-weight:700;text-transform:uppercase;color:#6b6050;">{{ cls }}</div>
            <div style="font-family:'JetBrains Mono',monospace;font-size:14px;font-weight:700;color:var(--ink);">{{ "%.0f"|format(recall) }}%</div>
            <div style="font-size:10px;color:#8b8270;">recall</div>
          </div>
          {% endfor %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- ── ROC CURVES ── -->
  <div class="section">
    <div class="section-title">ROC Curves (One-vs-Rest)</div>
    <div class="grid2">
      {% for model_name in ['Logistic Regression', 'Random Forest'] %}
      <div class="card">
        <div class="card-title">{{ model_name }}</div>
        <div class="chart-box" style="height:280px;">
          <canvas id="roc_{{ loop.index }}"></canvas>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- ── FEATURE IMPORTANCE ── -->
  <div class="section">
    <div class="section-title">Feature Importance</div>
    <div class="grid2">
      {% for model_name, caption in [
        ('Random Forest', 'Gini impurity reduction'),
        ('Logistic Regression', 'Mean |coefficient| across classes')
      ] %}
      <div class="card">
        <div class="card-title">{{ model_name }} <span style="font-size:11px;font-weight:400;color:#8b8270;">({{ caption }})</span></div>
        <div class="chart-box" style="height:300px;">
          <canvas id="fi_{{ loop.index }}"></canvas>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- ── DATASET ── -->
  <div class="section">
    <div class="section-title">Dataset Overview</div>
    <div class="grid2">
      <div class="card">
        <div class="card-title">Statistics</div>
        <div class="grid3" style="gap:10px;">
          <div class="metric-box"><div class="metric-label">Records</div><div class="metric-val">{{ ds.n_rows }}</div></div>
          <div class="metric-box"><div class="metric-label">Features</div><div class="metric-val">{{ ds.n_features }}</div></div>
          <div class="metric-box"><div class="metric-label">Classes</div><div class="metric-val">5</div></div>
          <div class="metric-box"><div class="metric-label">Train</div><div class="metric-val" style="font-size:18px;">{{ ds.train_size }}</div></div>
          <div class="metric-box"><div class="metric-label">Test</div><div class="metric-val" style="font-size:18px;">{{ ds.test_size }}</div></div>
          <div class="metric-box"><div class="metric-label">Split</div><div class="metric-val" style="font-size:18px;">80/20</div></div>
        </div>
      </div>
      <div class="card">
        <div class="card-title">Class Distribution</div>
        <div class="chart-box" style="height:200px;">
          <canvas id="classChart"></canvas>
        </div>
      </div>
    </div>
  </div>

</div>

<!-- ── ALL CHARTS JS ── -->
<script>
const LR_COLOR = '#14213d';
const RF_COLOR = '#c9852b';
const CLASSES  = {{ class_names|tojson }};
const GRADE_COLORS = ['#2f7a52','#3b7a5e','#b8860b','#b5651d','#a33b2c'];
const METRICS_LR = {{ metrics['Logistic Regression']|tojson }};
const METRICS_RF = {{ metrics['Random Forest']|tojson }};
const ROC_DATA   = {{ roc_data|tojson }};
const FEAT_IMP   = {{ feat_imp|tojson }};
const DS         = {{ ds|tojson }};

// ── Metric bar chart ──
new Chart(document.getElementById('metricChart').getContext('2d'), {
  type: 'bar',
  data: {
    labels: ['Accuracy','Precision','Recall','F1-Score','ROC-AUC'],
    datasets: [
      { label:'Logistic Regression', backgroundColor: LR_COLOR, borderRadius:3,
        data: [METRICS_LR.accuracy, METRICS_LR.precision, METRICS_LR.recall, METRICS_LR.f1_score, METRICS_LR.roc_auc] },
      { label:'Random Forest', backgroundColor: RF_COLOR, borderRadius:3,
        data: [METRICS_RF.accuracy, METRICS_RF.precision, METRICS_RF.recall, METRICS_RF.f1_score, METRICS_RF.roc_auc] },
    ]
  },
  options: { responsive:true, maintainAspectRatio:false,
    scales: { y:{ min:0, max:1, ticks:{callback:v=>Math.round(v*100)+'%'} } },
    plugins: { legend:{ position:'bottom' } }
  }
});

// ── Training time bar chart ──
new Chart(document.getElementById('timeChart').getContext('2d'), {
  type: 'bar',
  data: {
    labels: ['Logistic Regression','Random Forest'],
    datasets: [{ label:'Train Time (s)', borderRadius:4,
      backgroundColor: [LR_COLOR, RF_COLOR],
      data: [METRICS_LR.train_time_sec, METRICS_RF.train_time_sec] }]
  },
  options: { responsive:true, maintainAspectRatio:false,
    plugins: { legend:{ display:false } },
    scales: { y:{ title:{ display:true, text:'Seconds' } } }
  }
});

// ── ROC curves ──
['Logistic Regression','Random Forest'].forEach((model, idx) => {
  const canvas = document.getElementById('roc_'+(idx+1));
  const datasets = CLASSES.map((cls,i) => ({
    label: `Grade ${cls} (AUC=${ROC_DATA[model][cls].auc})`,
    data: ROC_DATA[model][cls].fpr.map((x,j) => ({x, y: ROC_DATA[model][cls].tpr[j]})),
    borderColor: GRADE_COLORS[i], backgroundColor:'transparent',
    borderWidth:2, pointRadius:0, tension:0.3,
  }));
  datasets.push({
    label:'Random', data:[{x:0,y:0},{x:1,y:1}],
    borderColor:'#ccc', borderDash:[4,4], borderWidth:1,
    pointRadius:0, backgroundColor:'transparent',
  });
  new Chart(canvas.getContext('2d'), {
    type:'line', data:{ datasets },
    options: { responsive:true, maintainAspectRatio:false,
      scales: {
        x:{ type:'linear', min:0, max:1, title:{display:true,text:'FPR'} },
        y:{ min:0, max:1, title:{display:true,text:'TPR'} }
      },
      plugins:{ legend:{ position:'bottom', labels:{ boxWidth:12, font:{size:10} } } }
    }
  });
});

// ── Feature importance ──
['Random Forest','Logistic Regression'].forEach((model, idx) => {
  const labels_map = FEAT_IMP.labels;
  const vals = FEAT_IMP[model];
  const sorted = Object.entries(vals).sort((a,b)=>b[1]-a[1]);
  const labels = sorted.map(([k])=> labels_map[k]||k);
  const data   = sorted.map(([,v])=>v);
  const canvas = document.getElementById('fi_'+(idx+1));
  new Chart(canvas.getContext('2d'), {
    type:'bar',
    data:{ labels, datasets:[{ label:'Importance', data,
      backgroundColor: idx===0 ? RF_COLOR : LR_COLOR, borderRadius:3 }] },
    options:{ indexAxis:'y', responsive:true, maintainAspectRatio:false,
      plugins:{ legend:{display:false} },
      scales:{ x:{ beginAtZero:true }, y:{ ticks:{font:{size:11}} } }
    }
  });
});

// ── Class distribution ──
new Chart(document.getElementById('classChart').getContext('2d'), {
  type:'doughnut',
  data:{
    labels: Object.keys(DS.class_counts).map(g=>`Grade ${g}`),
    datasets:[{
      data: Object.values(DS.class_counts),
      backgroundColor: GRADE_COLORS,
      borderWidth:2, borderColor:'#fff'
    }]
  },
  options:{ responsive:true, maintainAspectRatio:false,
    plugins:{ legend:{ position:'right', labels:{font:{size:11}} } }
  }
});
</script>

</body>
</html>
"""

# ─────────────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────────────
@app.route("/", methods=["GET", "POST"])
def index():
    result    = None
    submitted = None
    if request.method == "POST":
        submitted = {c: request.form.get(c, "0") for c in FEATURE_COLS}
        result    = run_prediction(submitted)
    return render_template_string(
        INDEX_HTML,
        result=result,
        submitted=submitted,
        class_names=CLASS_NAMES,
    )

@app.route("/compare")
def compare():
    return render_template_string(
        COMPARE_HTML,
        metrics=METRICS,
        roc_data=ROC_DATA,
        feat_imp=FEAT_IMP,
        ds=DS_SUMMARY,
        class_names=CLASS_NAMES,
        enumerate=enumerate,
        min=min,
    )

@app.route("/api/predict", methods=["POST"])
def api_predict():
    """
    JSON API endpoint.
    POST body: {"features": {"Age":16, "Gender":0, ...all 12 features...}}
    Returns predictions from both models.
    """
    payload  = request.get_json(force=True)
    features = payload.get("features", {})
    missing  = [c for c in FEATURE_COLS if c not in features]
    if missing:
        return jsonify({"error": f"Missing features: {missing}"}), 400
    try:
        result = run_prediction(features)
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 400

@app.route("/api/metrics")
def api_metrics():
    return jsonify(METRICS)

if __name__ == "__main__":
    print("\n  Starting Flask app...")
    print("  Prediction page    : http://127.0.0.1:5000/")
    print("  Comparison page    : http://127.0.0.1:5000/compare")
    print("  API endpoint       : http://127.0.0.1:5000/api/predict  [POST]")
    app.run(debug=True, port=5000)
